spring:
  datasource:
    driver-class-name: 0rg.h2.Driver
    url: jdbc:h2:~demodb
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true